// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CpuCoreInfo = { id: number, 
/**
 * CPU usage percentage [0.0..100.0]
 */
usage: number, 
/**
 * Current frequency in MHz if known
 */
frequency: number | null, 
/**
 * Current temperature in Celsius if available
 */
temperature: number | null, };
