// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CpuCoreInfo } from "./CpuCoreInfo.ts";
import type { TemperatureSensor } from "./TemperatureSensor.ts";

export type HwInfo = { cpus: Array<CpuCoreInfo>, otherTemperatures: Array<TemperatureSensor>, };
