#!/usr/bin/env sh
. "$(dirname -- "$0")/_/hook.sh"

deno check ./src/lib.ts
deno fmt --check
deno lint

cargo fmt -- --check
cargo clippy -- -D warnings
# cargo test # we skip this cuz cargo test generate files

deno test