// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FancyToolbarSettingsByMonitor } from './FancyToolbarSettingsByMonitor.ts';
import type { SeelenWallSettingsByMonitor } from './SeelenWallSettingsByMonitor.ts';
import type { SeelenWegSettingsByMonitor } from './SeelenWegSettingsByMonitor.ts';
import type { WindowManagerSettingsByMonitor } from './WindowManagerSettingsByMonitor.ts';
import type { WorkspaceConfiguration } from './WorkspaceConfiguration.ts';

export type MonitorConfiguration = {
  tb: FancyToolbarSettingsByMonitor;
  weg: SeelenWegSettingsByMonitor;
  wm: WindowManagerSettingsByMonitor;
  wall: SeelenWallSettingsByMonitor;
  /**
   * list of settings by workspace on this monitor
   */
  workspacesV2: Array<WorkspaceConfiguration>;
};
