// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeelenWallWallpaper } from './SeelenWallWallpaper.ts';

export type SeelenWallSettingsByMonitor = { enabled: boolean; backgrounds: Array<SeelenWallWallpaper> | null };
