// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeelenLauncherMonitor } from './SeelenLauncherMonitor.ts';
import type { SeelenLauncherRunner } from './SeelenLauncherRunner.ts';

export type SeelenLauncherSettings = {
  enabled: boolean;
  monitor: SeelenLauncherMonitor;
  runners: Array<SeelenLauncherRunner>;
};
