// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AhkVarList } from './AhkVarList.ts';
import type { FancyToolbarSettings } from './FancyToolbarSettings.ts';
import type { JsonValue } from './serde_json/JsonValue.ts';
import type { MonitorConfiguration } from './MonitorConfiguration.ts';
import type { SeelenLauncherSettings } from './SeelenLauncherSettings.ts';
import type { SeelenWallSettings } from './SeelenWallSettings.ts';
import type { SeelenWegSettings } from './SeelenWegSettings.ts';
import type { UpdaterSettings } from './UpdaterSettings.ts';
import type { VirtualDesktopStrategy } from './VirtualDesktopStrategy.ts';
import type { WidgetId } from './WidgetId.ts';
import type { WindowManagerSettings } from './WindowManagerSettings.ts';

export type Settings = {
  /**
   * fancy toolbar config
   */
  fancyToolbar: FancyToolbarSettings;
  /**
   * seelenweg (dock/taskbar) config
   */
  seelenweg: SeelenWegSettings;
  /**
   * window manager config
   */
  windowManager: WindowManagerSettings;
  /**
   * background and virtual desktops config
   */
  wall: SeelenWallSettings;
  /**
   * App launcher settings
   */
  launcher: SeelenLauncherSettings;
  /**
   * list of monitors and their configurations
   */
  monitorsV2: { [key in string]?: MonitorConfiguration };
  /**
   * enable or disable ahk
   */
  ahkEnabled: boolean;
  /**
   * ahk variables
   */
  ahkVariables: AhkVarList;
  /**
   * list of selected themes
   */
  selectedThemes: Array<string>;
  /**
   * list of selected icon packs
   */
  iconPacks: Array<string>;
  /**
   * enable or disable dev tools tab in settings
   */
  devTools: boolean;
  /**
   * language to use, if null the system locale is used
   */
  language: string | null;
  /**
   * MomentJS date format
   */
  dateFormat: string;
  /**
   * what virtual desktop implementation will be used, in case Native is not available we use Seelen
   */
  virtualDesktopStrategy: VirtualDesktopStrategy;
  /**
   * Updater Settings
   */
  updater: UpdaterSettings;
  /**
   * Custom settings for widgets
   */
  custom: { [key in WidgetId]?: { [key in string]?: JsonValue } };
};
