// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rect } from './Rect.ts';

export type WindowManagerSettingsByMonitor = {
  enabled: boolean;
  padding: number | null;
  margin: Rect | null;
  gap: number | null;
  layout: string | null;
};
