// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeelenWallWallpaper } from './SeelenWallWallpaper.ts';
import type { WorkspaceIdentifier } from './WorkspaceIdentifier.ts';

export type WorkspaceConfiguration = {
  identifier: WorkspaceIdentifier;
  layout: string | null;
  backgrounds: Array<SeelenWallWallpaper> | null;
};
